services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: barcode-v2-backend
    restart: unless-stopped
    ports:
      - "8034:8034"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8034
      - PYTHONUNBUFFERED=1
      - API_WORKERS=2
      - CORS_ORIGINS=http://localhost,http://localhost:8080,http://localhost:80,http://${DOMAIN:-localhost}
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/app.log
      - UPLOAD_DIR=/app/uploads
      - DOWNLOAD_DIR=/app/downloads
      - LOGS_DIR=/app/logs
    volumes:
      # Bind-mount local data directory to use existing DB
      - ./backend/data:/app/data
      - backend-uploads-v2:/app/uploads
      - backend-downloads-v2:/app/downloads
      - backend-logs-v2:/app/logs
      - backend-archives-v2:/app/archives
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8034/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - barcode-v2-network

  # Frontend (Nginx serving React build)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api
        - VITE_ENVIRONMENT=production
    container_name: barcode-v2-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - barcode-v2-network

  # Nginx Reverse Proxy (Optional - for production with single entry point)
  nginx-proxy:
    image: nginx:alpine
    container_name: barcode-v2-nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - barcode-v2-network
    profiles:
      - production

volumes:
  backend-data-v2:
    driver: local
  backend-uploads-v2:
    driver: local
  backend-downloads-v2:
    driver: local
  backend-logs-v2:
    driver: local
  backend-archives-v2:
    driver: local

networks:
  barcode-v2-network:
    driver: bridge


