version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: barcode-backend
    restart: unless-stopped
    ports:
      - "8034:8034"
    env_file:
      - ../backend/.env
    volumes:
      # Persist data
      - backend-data:/app/data
      - backend-uploads:/app/uploads
      - backend-downloads:/app/downloads
      - backend-logs:/app/logs
      - backend-archives:/app/archives
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8034/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - barcode-network

  # Frontend (Nginx serving React build)
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://${DOMAIN:-localhost}
        - VITE_ENVIRONMENT=production
    container_name: barcode-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - barcode-network

  # Nginx Reverse Proxy (Optional - for production with single entry point)
  nginx-proxy:
    image: nginx:alpine
    container_name: barcode-nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - barcode-network
    profiles:
      - production

volumes:
  backend-data:
    driver: local
  backend-uploads:
    driver: local
  backend-downloads:
    driver: local
  backend-logs:
    driver: local
  backend-archives:
    driver: local

networks:
  barcode-network:
    driver: bridge


